version: "3"
services:
  db:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: localdb
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass
      TZ: "Asia/Tokyo"
    volumes:
      - ./build/db/my.cnf:/etc/my.cnf
      - ./build/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  goapp:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    tty: true # コンテナの永続化
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./cmd:/go/src/app # マウントディレクトリ
