version: "3"
services: 
    goapp:
        build:
            context: .
            dockerfile: ./build/Dockerfile
        tty: true # コンテナの永続化
        volumes:
            - ./cmd:/go/src/app # マウントディレクトリ